### ISSUE TITLE
Backlight control via Anode vs BLK

### ISSUE THREAD

**Issue by holyape** [barn53/CoinThing#20]
Hi! Thanks for the fast response and resolving on pervious issue!

I got a noname Chinese devboard, which controls ST7789 backlight by using Anode (connected via transistor to GPIO5) instead of BLK (BLK is connected to GND).

<img width="352" alt="image" src="https://user-images.githubusercontent.com/125164776/220218991-98483942-3194-4b97-97cf-b12a0e7b4aea.png">

I have tried to just change TFT_BL PIN to D1 in Display.h file - backlight is still off.

Any suggestions on how to make it work?

**Comment by barn53** [comment]
too little detail.

**Comment by holyape** [comment]
I'm sorry, could you tell which additional detail I should provide from my side?

**Comment by barn53** [comment]
A schematic of the dev board, as it is important to know how exactly the backlight is driven.

**Comment by barn53** [comment]
Ok, the back light is not driven through a transistor, but directly through pin GPIO5.
In this case it should be enough to write in method Display::begin()

instead of :

analogWriteRange(std::numeric_limits<uint8_t>::max());
pinMode(TFT_BL, OUTPUT);
analogWrite(TFT_BL, std::numeric_limits<uint8_t>::max());


this:

pinMode(PIN_D1, OUTPUT);
digitalWrite(PIN_D1, HIGH);


But what you wrote on your first message, should have worked, too.
So I don't have a clue what's wrong.
Can you measure the voltage on GPIO5?

**Comment by holyape** [comment]
Unfortunately, doesn't work for me - I have tried to replace the piece of code you suggested and backlight is still off.

I'm not sure now if the schematic above is directly for my board - since there are no transistor as you noticed, but it is on board itself.

Yes, the voltage on GPIO5 is 3.13-3.14V

![IMG_2003](https://user-images.githubusercontent.com/125164776/222501662-cf0cb96e-2528-45bc-9138-90663e44cb45.jpg)
